### ISSUE TITLE
Table formatting does not work well with "pipe" in docstrings

### ISSUE THREAD

**Issue by BryanDiLaura** [alexkrechik/VSCucumberAutoComplete#382]
I have some scenarios where I use the pipe operator inside of some docstrings, but unfortunately the table formater doesn't handle it well. In an ideal world I thing one of two solutions would give me the desired behavior:

- If I turn on "Skip Doc Strings Format", don't run the table formatter or
- Only use the table formatting when there are greater than one '|' characters

Expected:
```
    Scenario: blah
        Given Some situation
        When I do some stuff
            """
                | this
                | is 
                | a 
                | pipe
            """

        Then expected thing happens
```

Actual:
```
    Scenario: blah
        Given Some situation
        When I do some stuff
            """
                ||
                ||
                ||
                ||
            """

        Then expected thing happens
```

**Comment by alexkrechik** [comment]
I like 'Only use the table formatting when there are greater than one '|' characters' solution.

**Comment by alexkrechik** [comment]
It should be fixed after 2.16.0 release

**Comment by ivtomash** [comment]
Hi there, have any updates with this issue?
My version is v2.15.2 and '|' character problem remains.

**Comment by alexkrechik** [comment]
This issue is to be fixed or implemented in the 3.0.0 version of the extension. If this issue is unresolved or there are additional notes, please create a new ticket with the necessary details.
